- hosts: all
  tasks:
     - name: delete old deployment
       command: microk8s kubectl delete -f /home/nasir/assets/deployment.yaml
       register: command_result
       # ignore_errors: true
       failed_when: command_result.rc != 1 and command_result.rc != 0
     - name: delete old service
       command: microk8s kubectl delete -f /home/nasir/assets/service.yaml
       register: command_result
       # ignore_errors: true
       failed_when: command_result.rc != 1 and command_result.rc != 0
     - name: create new deployment
       command: microk8s kubectl apply -f /home/nasir/assets/deployment.yaml
     - name: create new service
       command: microk8s kubectl apply -f /home/nasir/assets/service.yaml
