kind: Deployment
apiVersion: apps/v1
metadata:
   name: pl-demo
spec:
   replicas: 2
   selector:      # tells the controller which pods to watch/belong to
    matchLabels:
     app: pl-demo
   template:
      metadata:
        labels:
          app: devops
      spec:
       containers:
        - name: devops
          image: nasirhaider/pl-demo
          imagePullPolicy: Always
          ports:
          - containerPort: 80
